# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27bd3b5dd01ca1ecbde82b237020f43338028d873e78151115ac9408a36d3a63a4a8778e93b7dce4c07e90cf6cd4360580e7745487b60011c5e053f0eddb9ed5

test:
  secret_key_base: 89f85e0a4676030a5edd8f1da5830566835b1ae10969a418f48a15ea49ef75b197452a95c8df020a269f3b040589d57a80f90eacb6cea31fd84ebba139aafcfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
