# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 986d0251c90c2b42a801466657123d58553f2ff15837917c741bdce8c32cc366d845ea8dc581a65cabb1161b73a95de5fb0ce46b026dd07adc09f567f30e44de

test:
  secret_key_base: fc99c29969f8708fc31c90416246e342c5c9084d6a41b712cc22b50146383fa5a2876808b43d1af298d1ef52d96650b6b937e4cc599bab73ce8a3193bc343985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
